//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunmedyaAkademiPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAbout
    {
        public int AboutId { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
        public string DogumTarihi { get; set; }
        public string Website { get; set; }
        public string Telefon { get; set; }
        public string sehir { get; set; }
        public string Yas { get; set; }
        public string Egitim { get; set; }
        public string Email { get; set; }
        public string Freelance { get; set; }
    }
}
