//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunmedyaAkademiPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblproject
    {
        public int proectId { get; set; }
        public string proectTitle { get; set; }
        public string descripiton { get; set; }
        public string ımageUrl { get; set; }
        public int categoryId { get; set; }
    
        public virtual catagorytbl catagorytbl { get; set; }
    }
}
